"""
tests/functional/test_bookings_crud.py
========================================
Full CRUD lifecycle tests using Faker-generated synthetic data.

Data strategy:
  - Every payload is generated by BookingDataFactory, which embeds a UUID
    fragment in the lastname and the run_id in additionalneeds.
  - This guarantees zero collision across parallel workers, repeated runs,
    and shared staging environments — without sacrificing data realism.
  - The factory seed is logged on every test so any failure is 100%
    reproducible: grab the seed from the CI log, re-run locally.

Test philosophy:
  - Each test is INDEPENDENT. No shared mutable state between tests.
  - `created_booking` fixture guarantees teardown regardless of outcome.
  - Re-running this suite 100 times leaves the API in identical state.

Coverage matrix:
  ✅ CREATE           POST /booking — field persistence, ID assignment
  ✅ READ             GET  /booking/{id} — round-trip data integrity
  ✅ LIST             GET  /booking — filter by name, immediate consistency
  ✅ UPDATE (full)    PUT  /booking/{id} — full replacement semantics
  ✅ UPDATE (partial) PATCH /booking/{id} — field isolation
  ✅ DELETE           DELETE /booking/{id} — confirmed absence
  ✅ DELETE idempotency — repeat DELETE returns 404, not 500
  ✅ EDGE: max-length fields — truncation regression guard
  ✅ EDGE: zero price       — boundary value for financial fields
  ✅ EDGE: unicode names    — international character encoding
  ✅ FULL LIFECYCLE         — CREATE → READ → UPDATE → VERIFY → DELETE → CONFIRM
"""
from __future__ import annotations

import uuid
from datetime import date, timedelta

import pytest

from src.client.booking_client import BookingClient
from src.models.booking import BookingDates, BookingPayload, BookingResponse
from src.utils.data_factory import BookingDataFactory
from src.utils.logger import get_logger

logger = get_logger(__name__)


# ===========================================================================
# CREATE
# ===========================================================================


@pytest.mark.crud
class TestCreateBooking:

    def test_create_booking_returns_positive_integer_id(
        self,
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN a valid, Faker-generated booking payload
        WHEN  POST /booking is called
        THEN  the server returns a bookingid that is a positive integer
        AND   the response validates against the CreateBookingResponse contract

        Why this matters: a system that returns id=0, id=-1, or a string
        ID has a broken ID-generation sequence — a Tier-1 data integrity bug.
        """
        from conftest import deregister_from_cleanup, register_for_cleanup

        factory = BookingDataFactory()
        payload = factory.realistic()

        created = booking_client.create_booking(payload)
        register_for_cleanup(created.bookingid)

        try:
            assert isinstance(created.bookingid, int), (
                f"bookingid must be int, got {type(created.bookingid).__name__}"
            )
            assert created.bookingid > 0, (
                f"bookingid must be positive, got {created.bookingid}"
            )
            logger.info(
                "assert_create_id_valid",
                booking_id=created.bookingid,
                factory_seed=factory.seed,
            )
        finally:
            if booking_client.booking_exists(created.bookingid):
                booking_client.delete_booking(created.bookingid)
            deregister_from_cleanup(created.bookingid)

    def test_create_booking_persists_all_fields_exactly(
        self,
        created_booking: tuple[int, BookingPayload],
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN a booking is created with a specific Faker-generated payload
        WHEN  GET /booking/{id} is called immediately after creation
        THEN  every field in the response matches the original payload exactly

        This is the canonical data-integrity test. Silent field truncation,
        type coercion, or default-value substitution are all bugs that this
        test is specifically designed to catch.
        """
        booking_id, payload = created_booking
        retrieved = booking_client.get_booking(booking_id)

        assert retrieved.firstname == payload.firstname, (
            f"firstname: expected '{payload.firstname}', got '{retrieved.firstname}'"
        )
        assert retrieved.lastname == payload.lastname, (
            f"lastname: expected '{payload.lastname}', got '{retrieved.lastname}'"
        )
        assert retrieved.totalprice == payload.totalprice, (
            f"totalprice: expected {payload.totalprice}, got {retrieved.totalprice}"
        )
        assert retrieved.depositpaid == payload.depositpaid, (
            f"depositpaid: expected {payload.depositpaid}, got {retrieved.depositpaid}"
        )
        assert retrieved.bookingdates.checkin == payload.bookingdates.checkin, (
            f"checkin: expected {payload.bookingdates.checkin}, "
            f"got {retrieved.bookingdates.checkin}"
        )
        assert retrieved.bookingdates.checkout == payload.bookingdates.checkout, (
            f"checkout: expected {payload.bookingdates.checkout}, "
            f"got {retrieved.bookingdates.checkout}"
        )
        assert retrieved.additionalneeds == payload.additionalneeds, (
            f"additionalneeds: expected '{payload.additionalneeds}', "
            f"got '{retrieved.additionalneeds}'"
        )

        logger.info(
            "assert_round_trip_integrity_passed",
            booking_id=booking_id,
            firstname=retrieved.firstname,
        )

    def test_create_booking_is_immediately_discoverable(
        self,
        created_booking: tuple[int, BookingPayload],
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN a booking is created with a UUID-unique lastname
        WHEN  GET /booking?lastname=<unique_value> is called
        THEN  the new booking ID appears in the results

        Tests write-then-read consistency. A system with eventual consistency
        or a write-behind cache may pass the create call but fail this test.
        In a financial system, that is a Tier-1 incident.
        """
        booking_id, payload = created_booking
        results = booking_client.list_bookings(
            firstname=payload.firstname,
            lastname=payload.lastname,
        )
        result_ids = [b.bookingid for b in results]

        assert booking_id in result_ids, (
            f"Created booking {booking_id} not found in filtered list. "
            f"Searched: firstname={payload.firstname!r}, lastname={payload.lastname!r}. "
            f"Found IDs: {result_ids}"
        )

    def test_create_booking_with_max_length_fields(
        self,
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN a payload where all string fields are at maximum allowed length
        WHEN  POST /booking is called
        THEN  the API accepts it (no 400/422) and preserves fields without truncation

        Truncation at the API or database layer is a silent data loss bug.
        Max-length testing is mandatory for any field that stores user data.
        """
        from conftest import deregister_from_cleanup, register_for_cleanup

        factory = BookingDataFactory()
        payload = factory.max_length()

        created = booking_client.create_booking(payload)
        register_for_cleanup(created.bookingid)

        try:
            retrieved = booking_client.get_booking(created.bookingid)

            assert retrieved.firstname == payload.firstname, (
                "Max-length firstname was truncated. "
                f"Sent {len(payload.firstname)} chars, "
                f"got back {len(retrieved.firstname)} chars."
            )
            assert retrieved.lastname == payload.lastname, (
                "Max-length lastname was truncated."
            )
            logger.info(
                "assert_max_length_no_truncation",
                booking_id=created.bookingid,
                firstname_len=len(retrieved.firstname),
                factory_seed=factory.seed,
            )
        finally:
            if booking_client.booking_exists(created.bookingid):
                booking_client.delete_booking(created.bookingid)
            deregister_from_cleanup(created.bookingid)

    def test_create_booking_with_zero_price(
        self,
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN a booking payload with totalprice = 0
        WHEN  POST /booking is called
        THEN  the booking is accepted and price is stored as 0, not null/missing

        Zero-price records are a common edge case in financial systems.
        Some ORMs convert 0 to NULL or falsy values — this test catches that.
        """
        from conftest import deregister_from_cleanup, register_for_cleanup

        factory = BookingDataFactory()
        payload = factory.minimum_price()

        created = booking_client.create_booking(payload)
        register_for_cleanup(created.bookingid)

        try:
            retrieved = booking_client.get_booking(created.bookingid)

            assert retrieved.totalprice == 0, (
                f"Zero price was not preserved. Expected 0, got {retrieved.totalprice}. "
                "This may indicate a falsy-value substitution bug in the API."
            )
            logger.info(
                "assert_zero_price_preserved",
                booking_id=created.bookingid,
                factory_seed=factory.seed,
            )
        finally:
            if booking_client.booking_exists(created.bookingid):
                booking_client.delete_booking(created.bookingid)
            deregister_from_cleanup(created.bookingid)

    def test_create_booking_with_unicode_names(
        self,
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN a booking with names from non-Latin character sets (Japanese, Arabic, etc.)
        WHEN  POST /booking is called
        THEN  the booking is created and the names are stored without corruption

        International name support is non-negotiable for global financial platforms.
        Mojibake (character corruption from wrong encoding) is insidious because
        it often only appears on read, not on write.
        """
        from conftest import deregister_from_cleanup, register_for_cleanup

        factory = BookingDataFactory()
        payload = factory.unicode_names()

        created = booking_client.create_booking(payload)
        register_for_cleanup(created.bookingid)

        try:
            retrieved = booking_client.get_booking(created.bookingid)

            assert retrieved.firstname == payload.firstname, (
                f"Unicode firstname corrupted. "
                f"Sent: {payload.firstname!r}, got: {retrieved.firstname!r}"
            )
            assert retrieved.lastname == payload.lastname, (
                f"Unicode lastname corrupted. "
                f"Sent: {payload.lastname!r}, got: {retrieved.lastname!r}"
            )
            logger.info(
                "assert_unicode_preserved",
                booking_id=created.bookingid,
                firstname=retrieved.firstname,
                factory_seed=factory.seed,
            )
        finally:
            if booking_client.booking_exists(created.bookingid):
                booking_client.delete_booking(created.bookingid)
            deregister_from_cleanup(created.bookingid)


# ===========================================================================
# READ
# ===========================================================================


@pytest.mark.crud
class TestReadBooking:

    def test_get_booking_schema_is_fully_valid(
        self,
        created_booking: tuple[int, BookingPayload],
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN an existing booking
        WHEN  GET /booking/{id} is called
        THEN  the response cleanly deserializes into BookingResponse
        AND   all required fields are present with correct Python types

        Pydantic deserialization IS the schema assertion. A renamed field,
        wrong type, or missing required field raises ValidationError here
        before any manual assertion runs.
        """
        booking_id, _ = created_booking
        booking = booking_client.get_booking(booking_id)

        assert isinstance(booking, BookingResponse)
        assert isinstance(booking.firstname, str) and len(booking.firstname) > 0
        assert isinstance(booking.lastname, str) and len(booking.lastname) > 0
        assert isinstance(booking.totalprice, int) and booking.totalprice >= 0
        assert isinstance(booking.depositpaid, bool)
        assert booking.bookingdates.checkout > booking.bookingdates.checkin

    def test_get_nonexistent_booking_returns_404(
        self,
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN a booking ID that provably does not exist
        WHEN  GET /booking/{id} is called
        THEN  the API returns exactly 404

        Validates the error-path, not just the happy-path.
        A 500 here means the API crashes on unknown IDs — a server bug.
        """
        response = booking_client._client.get("/booking/2147483647")
        assert response.status_code == 404, (
            f"Expected 404 for non-existent booking, got {response.status_code}"
        )


# ===========================================================================
# UPDATE — Full Replacement (PUT)
# ===========================================================================


@pytest.mark.crud
class TestUpdateBooking:

    def test_put_replaces_all_fields(
        self,
        created_booking: tuple[int, BookingPayload],
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN an existing booking created with payload A
        WHEN  PUT /booking/{id} is called with a completely different payload B
        THEN  GET /booking/{id} returns values from B, not A

        The critical assertion is the final negative: that original values are
        GONE. A system that merges instead of replacing is violating PUT
        semantics — a subtle bug that causes financial record corruption.
        """
        booking_id, original_payload = created_booking

        factory = BookingDataFactory()
        update_payload = factory.realistic(
            checkin_offset_days=60,
            stay_duration_days=7,
        )

        updated = booking_client.update_booking(booking_id, update_payload)

        # Assert new values are present
        assert updated.firstname == update_payload.firstname
        assert updated.lastname == update_payload.lastname
        assert updated.totalprice == update_payload.totalprice
        assert updated.depositpaid == update_payload.depositpaid
        assert updated.bookingdates.checkin == update_payload.bookingdates.checkin

        # Assert original values are GONE (distinguishes PUT from PATCH)
        assert updated.firstname != original_payload.firstname, (
            "PUT returned the original firstname — API may be merging instead "
            "of replacing. This is a PUT-semantics violation."
        )

        # Round-trip verification: re-fetch to confirm persistence
        re_fetched = booking_client.get_booking(booking_id)
        assert re_fetched.firstname == update_payload.firstname, (
            "PUT appeared to succeed but re-fetch returned stale data. "
            "Possible write-behind cache or transaction isolation issue."
        )
        assert re_fetched.totalprice == update_payload.totalprice

        logger.info(
            "assert_put_round_trip_passed",
            booking_id=booking_id,
            factory_seed=factory.seed,
        )


# ===========================================================================
# UPDATE — Partial (PATCH)
# ===========================================================================


@pytest.mark.crud
class TestPatchBooking:

    def test_patch_updates_only_specified_fields(
        self,
        created_booking: tuple[int, BookingPayload],
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN an existing booking with known field values
        WHEN  PATCH is called with ONLY totalprice and depositpaid
        THEN  those two fields reflect new values
        AND   firstname, lastname, and dates are UNCHANGED

        Silently nulling unspecified fields is the most dangerous form of
        PATCH bug. In a financial system, it can zero out payment amounts
        or erase customer names without any error signal.
        """
        booking_id, original_payload = created_booking

        patch_data = {"totalprice": 9999, "depositpaid": False}
        patched = booking_client.partial_update_booking(booking_id, patch_data)

        # Patched fields must reflect new values
        assert patched.totalprice == 9999, (
            f"PATCH: totalprice expected 9999, got {patched.totalprice}"
        )
        assert patched.depositpaid is False, (
            f"PATCH: depositpaid expected False, got {patched.depositpaid}"
        )

        # Untouched fields must be byte-for-byte identical
        assert patched.firstname == original_payload.firstname, (
            f"PATCH corrupted firstname. "
            f"Expected '{original_payload.firstname}', got '{patched.firstname}'. "
            "PATCH must not modify unspecified fields."
        )
        assert patched.lastname == original_payload.lastname, (
            f"PATCH corrupted lastname."
        )
        assert patched.bookingdates.checkin == original_payload.bookingdates.checkin, (
            "PATCH modified checkin date — should not have touched date fields."
        )

        logger.info(
            "assert_patch_field_isolation_passed",
            booking_id=booking_id,
        )

    def test_patch_additionalneeds_to_null(
        self,
        created_booking: tuple[int, BookingPayload],
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN a booking with an additionalneeds value
        WHEN  PATCH sets additionalneeds to empty string
        THEN  the field is updated and no other fields are affected

        Nullable optional fields have a second bug class: setting them
        to empty/null may raise a 400 or be silently ignored.
        """
        booking_id, original_payload = created_booking

        patch_data = {"additionalneeds": ""}
        patched = booking_client.partial_update_booking(booking_id, patch_data)

        # Core fields must be untouched
        assert patched.firstname == original_payload.firstname
        assert patched.totalprice == original_payload.totalprice


# ===========================================================================
# DELETE
# ===========================================================================


@pytest.mark.crud
class TestDeleteBooking:

    def test_delete_booking_results_in_confirmed_absence(
        self,
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN a booking is created
        WHEN  DELETE /booking/{id} is called
        THEN  GET /booking/{id} returns 404 — the resource is provably gone

        This test manages its own full lifecycle because it MUST assert 404,
        which conflicts with the created_booking fixture's teardown assumption.
        The orphan registry is the safety net if the 404 assertion itself fails.
        """
        from conftest import deregister_from_cleanup, register_for_cleanup

        factory = BookingDataFactory()
        payload = factory.realistic()

        created = booking_client.create_booking(payload)
        booking_id = created.bookingid
        register_for_cleanup(booking_id)

        logger.info(
            "delete_test_resource_created",
            booking_id=booking_id,
            factory_seed=factory.seed,
        )

        booking_client.delete_booking(booking_id)
        deregister_from_cleanup(booking_id)

        assert not booking_client.booking_exists(booking_id), (
            f"Booking {booking_id} still accessible after DELETE. "
            "This is a data integrity failure: DELETE did not remove the resource."
        )
        logger.info("assert_resource_absent_post_delete", booking_id=booking_id)

    def test_delete_repeat_returns_404_not_500(
        self,
        booking_client: BookingClient,
    ) -> None:
        """
        GIVEN a booking is created and then deleted
        WHEN  DELETE is called a second time on the same ID
        THEN  the server returns 404 — NOT 500

        A 500 on a repeat DELETE means the server crashes on a missing record.
        This is an unhandled exception in the delete handler — a server bug
        that becomes an incident when retry logic fires twice.
        """
        from conftest import deregister_from_cleanup, register_for_cleanup

        factory = BookingDataFactory()
        payload = factory.realistic()

        created = booking_client.create_booking(payload)
        booking_id = created.bookingid
        register_for_cleanup(booking_id)

        booking_client.delete_booking(booking_id)
        deregister_from_cleanup(booking_id)

        # Second delete
        response = booking_client._client.delete(f"/booking/{booking_id}")
        assert response.status_code in {404, 405}, (
            f"Repeat DELETE on {booking_id} returned {response.status_code}. "
            "Expected 404. A 500 indicates the server crashes on unknown IDs."
        )


# ===========================================================================
# Full CRUD Lifecycle — the "money test"
# ===========================================================================


@pytest.mark.crud
class TestFullCrudLifecycle:

    def test_create_read_update_verify_delete_confirm(
        self,
        booking_client: BookingClient,
    ) -> None:
        """
        End-to-end CRUD lifecycle proof with Faker-generated data.

        This is the canonical integration test. Every phase uses Faker data:
          Phase 1 — CREATE  with a realistic payload
          Phase 2 — READ    and assert round-trip data integrity
          Phase 3 — UPDATE  with a completely new Faker payload
          Phase 4 — VERIFY  that the update persisted via re-fetch
          Phase 5 — DELETE  the resource
          Phase 6 — CONFIRM 404 — the resource is provably absent

        If this test passes, the full data pipeline is working correctly.
        If it fails, the structured log (with correlation ID and factory seed)
        gives enough context to reproduce and debug without re-running.
        """
        from conftest import deregister_from_cleanup, register_for_cleanup

        # Use a fixed seed for this lifecycle test so failures are reproducible
        factory = BookingDataFactory()
        booking_id: int | None = None

        try:
            # --- Phase 1: CREATE ---
            initial_payload = factory.realistic(checkin_offset_days=45, stay_duration_days=4)
            created = booking_client.create_booking(initial_payload)
            booking_id = created.bookingid
            register_for_cleanup(booking_id)

            assert booking_id > 0
            assert created.booking.firstname == initial_payload.firstname
            logger.info("lifecycle_phase_1_create_ok", booking_id=booking_id, seed=factory.seed)

            # --- Phase 2: READ ---
            retrieved = booking_client.get_booking(booking_id)

            assert retrieved.firstname == initial_payload.firstname
            assert retrieved.totalprice == initial_payload.totalprice
            assert retrieved.bookingdates.checkin == initial_payload.bookingdates.checkin
            logger.info("lifecycle_phase_2_read_ok", booking_id=booking_id)

            # --- Phase 3: UPDATE ---
            update_factory = BookingDataFactory()
            update_payload = update_factory.realistic(
                checkin_offset_days=90,
                stay_duration_days=14,
            )
            updated = booking_client.update_booking(booking_id, update_payload)

            assert updated.firstname == update_payload.firstname
            assert updated.totalprice == update_payload.totalprice
            assert updated.firstname != initial_payload.firstname, (
                "PUT did not replace firstname — merge bug suspected"
            )
            logger.info(
                "lifecycle_phase_3_update_ok",
                booking_id=booking_id,
                update_seed=update_factory.seed,
            )

            # --- Phase 4: VERIFY update persisted (round-trip) ---
            re_fetched = booking_client.get_booking(booking_id)

            assert re_fetched.firstname == update_payload.firstname, (
                "Update did not persist — stale read after PUT. "
                "Possible caching or consistency issue."
            )
            assert re_fetched.totalprice == update_payload.totalprice
            logger.info("lifecycle_phase_4_verify_ok", booking_id=booking_id)

            # --- Phase 5: DELETE ---
            booking_client.delete_booking(booking_id)
            deregister_from_cleanup(booking_id)
            logger.info("lifecycle_phase_5_delete_ok", booking_id=booking_id)

            # --- Phase 6: CONFIRM absence ---
            assert not booking_client.booking_exists(booking_id), (
                f"Booking {booking_id} still reachable after DELETE. "
                "Data integrity failure at the delete phase of the lifecycle."
            )
            logger.info(
                "lifecycle_all_phases_passed",
                booking_id=booking_id,
                initial_seed=factory.seed,
                update_seed=update_factory.seed,
            )

        except Exception:
            # Orphan registry handles cleanup. Re-raise for pytest.
            raise
